// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAirJpvGxlOuTk0J66jFr6OQAWyh6lvOCQ',
    appId: '1:167200593722:web:64b1fba98392ea43cc2203',
    messagingSenderId: '167200593722',
    projectId: 'chat-95f80',
    authDomain: 'chat-95f80.firebaseapp.com',
    storageBucket: 'chat-95f80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTkauQRN6KxsEWL7te4eojzk24qqAtm0',
    appId: '1:167200593722:android:5a1cae9e20a396cccc2203',
    messagingSenderId: '167200593722',
    projectId: 'chat-95f80',
    storageBucket: 'chat-95f80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiA9Dd7_a7D-O_RHBBn0bL09M6wo0crHM',
    appId: '1:167200593722:ios:439a18a9fb902250cc2203',
    messagingSenderId: '167200593722',
    projectId: 'chat-95f80',
    storageBucket: 'chat-95f80.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiA9Dd7_a7D-O_RHBBn0bL09M6wo0crHM',
    appId: '1:167200593722:ios:b3518bba52198773cc2203',
    messagingSenderId: '167200593722',
    projectId: 'chat-95f80',
    storageBucket: 'chat-95f80.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
